### ISSUE TITLE
Automatic format retrieval option

### ISSUE THREAD

**Issue by TwistTheNeil** [meeb/tubesync#10]
If it's possible, it would be nice to see an option which automatically picks the best video resolution and audio using youtube-dl's -f `bestvideo+bestaudio` param instead of selecting manually an option in the source configuration

Perhaps this was the intention with the fallback. But i'm still selecting the highest known video resolution and an audio codec

PS nice project, just stumbled on it. Hope to replace my cronjob mess soon!

**Comment by meeb** [comment]
Sure this might be a reasonable idea. I actually went to some lengths to re-implement the resolution and format detection to do what I wanted (best possible quality for the format with 60fps/hdr if available etc.) but the youtube-dl's 'best' is probably fine for a lot of other use cases as well. I'll see how sensible it is to add it. Thanks for the suggestion.

**Comment by TwistTheNeil** [comment]
Thanks @meeb :)

**Comment by TwistTheNeil** [comment]
I'll look into the fallback option more tomorrow or over the weekend. I set it to 8k and tested with one channel and it seemed to get the correct video format but there were audio codecs with higher bitrate which was missed (different codec).

**Comment by meeb** [comment]
Ah, well you can just pick a different audio codec if you prefer, it'll match the desired codec at the highest bitrate over the highest general bitrate. If you find a video with some codec I've not found in my testing (not OPUS or M4A) spam the link in here and I'll add support for it.

**Comment by meeb** [comment]
After some poking about, this is going to be a pain to implement with the existing manual selection of codecs and resolutions implemented in TubeSync. I'll close this for now, but comment back on the issue or open a new more specific details if you find the current media format selection system isn't doing what you want. Personally, I'd prefer TubeSync kept better specific per-format selection in it rather than passing it off to `youtube-dl` which may change as the upstream is updated.

**Comment by TwistTheNeil** [comment]
Alright, yeah, no worries! Thanks for the update!
