### ISSUE TITLE
--add-metadata/--embed-thumbnail option for sources

### ISSUE THREAD

**Issue by HStep20** [meeb/tubesync#111]
As of now, its possible to write .nfo files of the metadata when downloading, however Plex doesn't use .nfo from what I understand. 

I know youtube-dl has the tag --add-metadata and --embed-thumbnail to write the metadata/thumbnail directly into an mp4 formatted file, making importing into Plex libraries seamless. Ive done it with manual cmd youtube-dl downloads in the past, but it'd be a great option for those who use Plex.

**Comment by meeb** [comment]
Yep this absolutely should be in TubeSync and is probably something I've just overlooked.

**Comment by meeb** [comment]
I've had a bit of testing with this and the bundled libraries used (`youtube-dl` uses `ffmpeg` which in turn uses `AtomicParsley`) can embed metadata, however `AtomicParsley` which is used for thumbnail embedding only supports MP4 containers not MKV containers. I'll add in metadata embedding, but not thumbnail embedding by default right now as MKV containers are the default TubeSync uses.

**Comment by meeb** [comment]
It turns out passing the required flag to ffmeg as a post-processor to embed metadata was trivial to add if not in the documented list of options. This is now in the `:latest` image. However, this is the same as adding the default `--add-metadata` flag on command line rather than doing anything particularly fancy.

As for the thumbnails, I'll wait until the pending pull requests for `youtube-dl` to support thumbnails in MKV containers are merged before implementing it, ref:

https://github.com/ytdl-org/youtube-dl/pull/15445
https://github.com/ytdl-org/youtube-dl/issues/28601

**Comment by jkexbx** [comment]
Was embedding thumbnails support ever added?

**Comment by meeb** [comment]
Ah, thanks for the reminder. Embedded thumbnail support was not added so far, however the blocker for this was pending patches to `youtube-dl` which TubeSync no longer uses. It's likely I can implement this now without much hassle assuming `yt-dlp` supports this feature which I believe it now does.

**Comment by deefdragon** [comment]
What is the current status of this issue?
The _option_ exists on the front end, but this was never closed, and, I'm not getting any thumbnails. 

As far as I can tell, none of the files I have downloaded are getting the thumbnail embedded, but they are also all audio files, not video, and Im not sure of youtube-dl supports that for audio files.

**Comment by meeb** [comment]
Thanks for the reminder on the open issue. This has been added for quite some time now, ever since the internal API version of `--add-metadata` was added and enabled. See

https://github.com/meeb/tubesync/blob/main/tubesync/tubesync/settings.py#L162

So, effectively tubesync *is* calling `--add-metadata` and has been for a long time.

If you have a particular issue or setup where metadata isn't being added @deefdragon that's probably a different issue or needs specific, additional metadata handling to work.
