### ISSUE TITLE
Skip does not work

### ISSUE THREAD

**Issue by Cycor** [meeb/tubesync#119]
I can't skip a video, the log says

2021-05-11 10:47:37,164 [tubesync/INFO] Media: Ty Palowski / -y8CHWx6aGY has a valid publishing date, marking to be unskipped

I'm using the :latest docker

**Comment by meeb** [comment]
The logic flow that causes this bug is a bit sticky, it's triggered when you've set a max media age to download on a source and then attempt to manually skip the media. Internally the skip flag is used to mark media that's too old to download based on the source max download age setting as well, which is where the issue occurs. It thinks as the media is new enough to download that it should then unskip the media.

Mostly explaining this so I can review it when I get a chance to fix it.

The fix is to probably add another field for `is_too_old` or similar, or not use flags for age and compare dates directly in SQL instead to keep the manual skip flag separate from the media age checks.

**Comment by Ateroz** [comment]
I'm seeing this same error when skipping videos on a source without a max age. This is happening to me when I'm attempting to skip a few old videos that try to download in DASH format. My source is set to keep all media and has no download cap.

For example, https://www.youtube.com/watch?v=NBj2_Sc-wLM.

**Comment by karolisr** [comment]
Is there any possible workaround for this issue while it is still open; some way to delete unwanted videos to save space? I tried to delete the files manually, but it gets redownloaded the moment the sync task runs again. Thanks.

**Comment by meeb** [comment]
Bit messy, but you can always just actually delete the video file off the disk. It won't be automatically detected as missing and re-downloaded at the moment.

**Comment by meeb** [comment]
This should have been fixed for some time. Please open a new issue if you still experience this.
