### ISSUE TITLE
Losing connections to mariadb/mysql

### ISSUE THREAD

**Issue by Code-Slave** [meeb/tubesync#121]
I will frequently get a lost connection to mysql erro. It leaves a process in a locked state and most times a worker has timed out. this this is latest error. It finished a video then looks like it resheduled it? and lost connect

2021-05-16 21:25:20,299 [tubesync/INFO] [youtube-dl] finished downloading: 2018-10-22_aprilwilkerson_building-a-log-hauling-trailer_uI6kC2YN1Oc_1080p-vp9-opus.mkv.f251 - 9.84MiB in 03:01

2021-05-16 21:25:21,570 [tubesync/INFO] Successfully downloaded media: uI6kC2YN1Oc (UUID: ac8d4c75-11b0-4275-b2ec-88d4e6f42371) to: "/downloads/video/aprilwilkerson/2018/2018-10-22_aprilwilkerson_building-a-log-hauling-trailer_uI6kC2YN1Oc_1080p-vp9-opus.mkv"

Rescheduling Downloading media for "Building A Log Hauling Trailer"

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/mysql/base.py", line 73, in execute

    return self.cursor.execute(query, args)

  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 206, in execute

    res = self._query(query)

  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 319, in _query

    db.query(q)

  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/connections.py", line 259, in query

    _mysql.connection.query(self, query)

MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

**Comment by meeb** [comment]
Hm, you can code in client-side retry code but that basically just retries stuff until MySQL accepts it but this seems to be a configuration or hosting error, are any of the described situations here applicable to your setup?

https://dev.mysql.com/doc/refman/5.7/en/error-lost-connection.html

It may be queries executed after the maximum connection time in the MySQL connection driver failing in the worker process, but this really should be handled by the connection pool automatically. If none of those configuration options work I'll add in some hacky loop that "tests" MySQL is alive but that's the last solution I'd like to try.

**Comment by Code-Slave** [comment]
What im seeing I think is that ytdl is being throttled so dl is like 50kbs which cause the timeout maybe as the dl takes like 30 min to finish. So maybe that worker is timining out?

**Comment by meeb** [comment]
That might be contributing, but really the database should be fine with permanently open connections. MySQL doesn't handle this well so situations where the client thinks the connection is open because it hasn't errored or closed but when the client attempts to send a query the server throws an error occur. It's a regular annoyance for any project I've developed with long running background tasks and MySQL database backends. You can work around it, it's just messy.

**Comment by Code-Slave** [comment]
Might need to add some cleanup to background process then. Cause when its locked by the pid of a crashed worker it never clears and holds the que up

**Comment by meeb** [comment]
Stuck tasks should auto-retry eventually, also failed tasks should have nothing to do with MySQL connection errors, they're different issues. If the tasks aren't retrying that's another (different) bug!

**Comment by Code-Slave** [comment]
This is getting pretty consistant

`
2021-05-17 12:14:18,961 [tubesync/INFO] Successfully downloaded media: VKznDtqNrhQ (UUID: 43c5e6e3-5a79-46f3-af1b-2cf01bfb16a0) to: "/downloads/video/aprilwilkerson/2017/2017-10-08_aprilwilkerson_making-a-walking-cane-for-my-dad-without-a-lathe_1080p-vp9-opus_[VKznDtqNrhQ].mkv"

Rescheduling Downloading media for "Making a Walking Cane For My Dad - Without a Lathe"

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/mysql/base.py", line 73, in execute

    return self.cursor.execute(query, args)

  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 206, in execute

   res = self._query(query)

  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)

MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
`

**Comment by meeb** [comment]
Does that download consistently take longer than 300 seconds?

**Comment by Code-Slave** [comment]
its a diff dl, but sometimes fast and sometimes slow. but yes they are both more than 300 seconds. its interesting it says completed, then reschedules it

**Comment by meeb** [comment]
OK that makes sense, in a summarised list what happens when a download task is triggered is:

1. The task gets the media item
2. Starts `youtube-dl` off on a download
3. Waits for `youtube-dl` to complete
4. Marks the media item in tubesync as "downloaded"

Now of the download technically completes via `youtube-dl` but step 4. doesn't happen then there's no way to know if the download was ACTUALLY successul, so it will attempt to download it again assuming the worst (that the download failed in some way). There isn't a file hash or anything you can compare against later to verify the download was successful.

The reason I asked about 300 seconds is that's currently the `CONN_MAX_AGE` set for the database connection. I think this can be solved with MySQL config tweaks, but to be honest this is very silly and requiring people to hack their `my.ini` files to make an application work is also very silly so I'll look at the "connection retry" hacks that others have discussed in other projects.

Of course, Postgres doesn't have these problems!

I'll push a patch which attempts to fix this when I get a moment. It might require a couple of attempts to get right.

**Comment by Code-Slave** [comment]
im going to spin up another with pg and test too. Ill test maria/mysql of course but have no issues running pg if its a better experience

**Comment by Code-Slave** [comment]
Hah. what a hug diff in pg vs mysql/maria. going through all the reset tasks etc that would quickly break and no issues in pg so far

**Comment by meeb** [comment]
Glad to hear that's working better. You can of course get MySQL to behave as well, it's just not as co-operative with very long running connections out of the box as Postgres. With MySQL you might find it works if you set this in your config:

```
[mysqld]
wait_timeout = 2880000
interactive_timeout = 2880000
```

Or similarly massive numbers.

**Comment by meeb** [comment]
Just to be annoying, I'm going to re-open this as I am going to try some tubesync-side hacks to improve MySQL support and I'll track it in this ticket.

**Comment by Code-Slave** [comment]
ping me if you want/need some testing. im running mysql and pg side by side

**Comment by meeb** [comment]
Almost certainly will do, thanks!

**Comment by meeb** [comment]
I've just pushed a keep-alive hack that should resolve the MySQL connection issues. Please pull `:latest` and give it a go on MySQL. If you still get any MySQL connection problems please re-open this ticket with some logs and I'll look into it again. Thanks!
