### ISSUE TITLE
Cant find a way to download mp4 instead of mkv

### ISSUE THREAD

**Issue by boognish43** [meeb/tubesync#131]
Ive found the mp4 files I download from youtube play nicer with all of the various players etc i use. I cant find a way to download them through this program though, everything ive chosen codec wise in the settings still defaults to mkv, is there a way?

thanks so much for the awesome software!

**Comment by boognish43** [comment]
I realized theres a good amount, maybe all videos that only download in 2k and 4k in mkv format. Im going to just go this route. thanks again for this amazing software!

**Comment by meeb** [comment]
MKV was chosen as the default container format because it was more flexible in the permitted combinations of audio and video codecs than MP4. In early builds there was an option to choose between MKV and MP4, but this became complicated as when you chose some combinations of preferred codecs TubeSync would have to know which worked for what format to throw an error if they were invalid. This got annoying and complicated so I just hard-coded it as MKV as the default video container format. Thanks for the complements as well!
