### ISSUE TITLE
Cannot download any youtube video

### ISSUE THREAD

**Issue by sebastienvermeille** [meeb/tubesync#137]
Hi, unfortunately I cannot make it working and I really need this tool it's great (I like to listen to some videos as podcasts more than watching them when I am walking)

Here are the infos I could retrieve:

TubeSync version: 0.9.1
Youtube-dl version: 2021.03.03
FFmpeg version: 4.3.1-static

Note: I installed this from unraid "app store".

Errors:
In tasks:
```
Error: "Failed to extract_info for "https://www.youtube.com/channel/UC5X4e8ScZI2AFd_vkjSoyoQ/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff."
```

I tried to use the tag :latest for the docker image and this one works.

**Comment by meeb** [comment]
Yes 0.9.1 currently uses an outdated version of `youtube-dl`. `:latest` should work. I'll update the readme shortly.

**Comment by meeb** [comment]
Closing due to assuming your issue was solved. Comment again if you're still having issues.

**Comment by Jleagle** [comment]
I have started to get this too

```
Index media from source "headsqueeze", attempted 4 times
Error: "Failed to extract_info for "https://www.youtube.com/c/headsqueeze/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff."
Task will be retried at 2022-01-17 14:31:18
```

I don't think its an issue with youtube-dl as other sources work okay.

**Comment by meeb** [comment]
"headsqueeze" is a vanity / whatever it's called / short name for the channel. The actual channel name for that channel is "UCdsOTr6SmDrxuWE7sJFrkhQ".

Try editing the source and replacing the "key" with "UCdsOTr6SmDrxuWE7sJFrkhQ".

**Comment by Jleagle** [comment]
Edited the key and waited for a retry and got this:

```
Index media from source "headsqueeze", attempted 7 times
Error: "Failed to extract_info for "https://www.youtube.com/c/UCdsOTr6SmDrxuWE7sJFrkhQ/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff."
Task will be retried at 2022-01-17 15:43:43
```

**Comment by meeb** [comment]
You'll also need to set the source "type" to "YouTube channel by ID" as you're using the channel ID.

**Comment by Jleagle** [comment]
Thanks, think that solved it, bit confused how this happened though as i just entered https://www.youtube.com/headsqueeze into the validate form and it filled out the keys etc for me.

**Comment by meeb** [comment]
It's not anything you did. Some of the short URLs like youtube.com/namehere aren't channels. Or they're aliases to other channels. This means some the channel names only work on some URLs and not others.

In your case youtube.com/headsqueeze is some alias to a playlist or something else, more like a vanity URL. They're more of a pain to add and you have to reference them by channel ID. If you go to youtube.com/headsqueeze then "videos" and click the first video, which is this one:

https://www.youtube.com/watch?v=pFK1fHUZzk8

Then click the name of the channel under the video, it will take you here:

https://www.youtube.com/channel/UCdsOTr6SmDrxuWE7sJFrkhQ

Which is the ID of the channel I pasted above. You can identify vanity channel names because they don't work with the /c/ URL, so this 404s:

https://www.youtube.com/c/headsqueeze

Where as an actual channel with a name works with a /c/ URL, like this one:

https://www.youtube.com/c/TomScottGo

I'm sure there's more accurate terms to use and a reason for it on YouTube's end but I don't know them.
