### ISSUE TITLE
A Re-download all button for each source

### ISSUE THREAD

**Issue by HStep20** [meeb/tubesync#140]
I've run into a little UX problem of what happens when I delete the files in the download directory instead of through the UI of TubeSync. After setting up a source and downloading a few videos from it, I realized the name was wrong. I deleted the files and edited the source, only to find that the deleted files were still marked as downloaded.

I expect the behavior to work like Sonarr/Radarr where it recognizes the file is deleted, and prepares a task to download it again with the new settings set in the profile. (Im fairly certain it doesn't work this way, but maybe I'm wrong here.)

I see that there is an 'episode by episode' option to redownload media, but when you're looking at a channel with a large amount of videos, it is unfeasible to do it manually. I think the band-aid solution of a 'redownload all' button on each 'Source' would be best, if plans for file monitoring are not on the roadmap.

**Comment by meeb** [comment]
There was originally a re-download for source button in a very early version but I removed it because a single click might cause someone to download terabytes of data so it was a bit of a landmine. The file monitoring is probably more sensible so I'll create an issue for that. Thanks for the suggestion!

**Comment by meeb** [comment]
I've created issue #141 to track this so I'll close this issue.
