### ISSUE TITLE
Convert Thumbnail to PNG option

### ISSUE THREAD

**Issue by ngInit** [meeb/tubesync#165]
I'm not a fan of lossly formats for any data for that I plan on keeping long-term. So for posters and thumbnails I convert them to PNG format. It would be nice to have an option (per channel, because I don't care about this for the daily stuff that'll get deleted) to properly convert the thumbnail to a PNG.

I haven't noticed any webm thumbnails being saved through tubesync, so I'm guessing you're already doing some conversion to jpg? If that's the case, hopefully something like this would be simple. Unless there's a flag on youtube-dl that I'm unaware of that only downloads jpg thumbnails...

**Comment by meeb** [comment]
Yes the thumbnails are all converted to JPEG at the moment. YouTube presents thumbnails and headers in multiple formats, JPEG, WEBP and seemingly occasionally PNG and even GIF. It was logical to pick a common one to standardise the format. Downscaling PNG images to smaller PNG images or converting JPEGs to PNGs will still be a lossy operation, you would only keep it lossless by keeping original PNG or WEBP images where available. The thumbnails TubeSync saves at the moment are quite small.

I can see the point of your request, but this might be better as a "save original YouTube format verbatim as additional metadata" rather than different thumbnail formats. Changing the current thumbnail saving to PNGs wouldn't stop loss and just make the images larger.

**Comment by ngInit** [comment]
While it's true it'll still technically be lossly, the png format would stop the image from becoming more lossly if it's ever edited and resaved in the future. And I have enough storage for the minor size increase to not matter.
