### ISSUE TITLE
channels not being scanned

### ISSUE THREAD

**Issue by gregzuro** [meeb/tubesync#182]
here's the config for a source:

```
Index schedule | Every 12 hours
Download media? |  (checked)
Created | 2021-03-30 21:00:00
Last crawl | 2021-09-11 12:26:36
```

No task is ever scheduled for this source.

TubeSync version 0.10.0 with  yt-dlp version 2021.09.02 and  FFmpeg version 4.3.2-static.

**Comment by meeb** [comment]
Have you tried resetting your tasks? There's  a button for it at the bottom of the "tasks" page. If you have a lot of sources and media and that times out there's a command line option you can use which has no time limit.

**Comment by gregzuro** [comment]
Yes. Dozens of times.

**Comment by meeb** [comment]
OK, what's the channel or playlist you've added that's not working? And what is the "key" that's added in TubeSync? Also anything in the logs for this source?

**Comment by meeb** [comment]
Also pull the latest container, you're running an out of date version.

**Comment by MatthK** [comment]
Same issue here. I have 10 channels and I recently noticed that there were only 4 scheduled tasks. I reset the tasks, hoping it would pick up the missing ones again, but that didn't help.

Just pulled the latest image (Version 0.10.0) and reset the tasks again. But after an initial burst of tasks, it settled again at only 4 tasks for 4 of the 10 channels.

One of the channels that is monitored is this one here: https://www.youtube.com/channel/UC7sDT8jZ76VLV1u__krUutA (every 24 hours)
One of the channels that is missing is this one here: https://www.youtube.com/channel/UCHnyfMqiRRG1u-2MsSQLbXA (should be every 12 hours)

And I couldn't find anything on those missing channels in the log since the restart.

**Comment by meeb** [comment]
Did you use the reset tasks button or the command line to reset the tasks? I've actually got some time to work on this now so this will improve relatively soon anyway,

**Comment by MatthK** [comment]
I used the button in the Web interface.

**Comment by meeb** [comment]
The current reset tasks process is to delete all tasks, then trigger a check on every media item to see if it has anything that needs to be re-setup as a task. This is pretty slow. The web interface has a maximum execution time of 60 seconds so if the reset tasks process currently takes longer than 60 seconds it manages to get through a bunch of media, then gets killed before it can finish the rest. This is why you're resetting tasks and seeing 4/10 channels scheduled as tasks.

You can use the command line option which has no time limit to reset the tasks properly for now. This tasks system has been less than reliable which is why I'm attempting to replace it in the first place.

You can follow the guide here to use the command line option, it's one command so it's not anything in-depth:

https://github.com/meeb/tubesync/blob/main/docs/reset-tasks.md

**Comment by MatthK** [comment]
Thanks, that seems to have done the trick. I got 10 tasks scheduled again.

**Comment by gregzuro** [comment]
I tried this manual reset as well.  It looked good at first, but then:
![Screen Shot 2021-11-16 at 10 27 29](https://user-images.githubusercontent.com/235511/142044288-58328696-8f01-4525-90cb-d5af416925bf.png)

**Comment by rickydg** [comment]
I’m trying to reset the tasks from the command line from within the docker on unraid. Just keep getting permission denied. I ran `chmod +x` on manage.py and now get `/use/bin/env: ‘python’: no such file or directory`

**Comment by meeb** [comment]
It's `python3` not `python` in the container @rickydg .

**Comment by rickydg** [comment]
Great, dumb moment done with for the day!

**Comment by meeb** [comment]
As said a lot above, soon there will be no requirement to reset tasks and the button will be removed entirely.

**Comment by rickydg** [comment]
Amazing, looking forward to it. Great job with this, I love being able to watch pootube without adds, in plex too.

**Comment by gregzuro** [comment]
This manual reset fixed things.

Tubesync seems to be working smoothly for me for the first time, ever! 

Thanks!
