### ISSUE TITLE
Tasks Processing Idea

### ISSUE THREAD

**Issue by rrediske** [meeb/tubesync#267]
I haven't been keeping up on all of the GitHub issues and suggestions, but in 257 you said you were considering rewriting the tasks system and in 260 you talk about dealing with a large number of thumbnails, so I had an idea.

TLDR: Consider adding an option to skip indexing/downloading/thumb-nailing videos from more than a year ago (or some reasonable age). Maybe allow the user to tell tubesync to completely ignore all processing of videos older than x date. My fresh tubesync container processed 21,415 tasks over the first two days it was up, just to download videos from last week (20 videos). I only have 7 YouTube channel sources.

The detail; stating my use case
First, I'm a little concerned that YouTube may (or does?) throttle or block users that slam their servers with ten thousand or more requests per day. That level of activity may raise suspicion.

I just created a fresh container Saturday and started adding my 7 YouTube channel sources. My goal is mostly to watch new "episodes" of YouTube tech channels as soon as they come out. The last thing tubesync processes after adding a new source is to actually download the video (understandably). Given this, I only added the next channel after letting the old one finish completely, so that I could have the most recent videos ready to watch sooner. I also knew to add the smaller channels first, during the day, while I could monitor their progress and allow them to grab the latest videos before adding the massive 5000+, 10+ years old channels to get processed while I slept.

I don't think my docker VM is resource starved. It's running on a dual Xeon 24 core CPU and the docker VM rarely peaked over 1% CPU usage during the weekend. It's only using 3 GB of the 8 GB of RAM it has allocated. My Internet is stable with 300-400 Mbit download, so I don't think that's a factor, either. To be fair, completing around 10 tubesync tasks per minute on average isn't bad performance. It's just that 20,000+ tasks is a lot to think about.

**Comment by rrediske** [comment]
I forgot to add, a couple of the YouTube channels give "nginx 502 Bad Gateway" when I try to open them in the tubesync GUI to check, edit or delete. It tends to be the large channels, so I wonder if it's related to database lag from SQLite having so many entries? I'm not a coder :(

**Comment by meeb** [comment]
The timeout is effectively the operation took longer than 59 seconds, using Postgres as a backend may help. There's a bunch of command line commands you can use which have no timeout as a hack for now (see readme).

With regards to the indexing, yes the thumbnails could be selected better probably, however there will still need to be one request per media item to get its metadata so if you add a large channel there's not really any way other to handle it other than make a few thousand requests. The thumbnail requests are to a CDN so unlikely to trigger anything, but the metadata requests can. This is why the workers were scaled down to 1 and there's some light throttling in the processes that do run. In initial testing it was perfectly possible to process thousands of tasks per minute, however you did get your IP very quickly throttled by YouTube which is why the current task rate is comparatively very slow.

**Comment by rrediske** [comment]
I appreciate your reply and I understand what you're saying. I'll have to get Postgres a shot, though I normally don't need to do anything with the sources once I set them up, so I'll probably put that off until some day this winter when I'm bored and snowed in :)

Thank you for creating such a wonderful tool to automatically download YouTube videos!

**Comment by meeb** [comment]
No problem, thanks for the discussion.
