### ISSUE TITLE
Feature Request: Auto Skip Downloading Shorts

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [meeb/tubesync#279]
Could we get an option added to allow auto skipping downloading any shorts? I know on the YouTube website all the shorts have a special icon, so there might be a flag on the video that YouTube-DL can detect. If there's not, YouTube shorts also have a 60second maximum duration, so you could auto filter videos with a duration of 60 seconds or less.

**Comment by meeb** [comment]
Yep, a sensible request. Should be relatively easy to implement.

**Comment by ngInit** [comment]
If it would be more helpful in the long run, rather than a single checkbox for shorts, adding a more generalized filters section would be useful. Things like...

- title includes/excludes a string
- duration longer/shorter than number 
  - 60 secs is the max for shorts, so if there's no short flag to create a checkbox a user could just put 60 seconds here
  - some channels release short form advertisements or other videos that could be skipped by tweaking this duration

**Comment by meeb** [comment]
Yep, I believe keyword filtering and more verbose time limit filters are already discussed on another wishlist ticket.

**Comment by alneven** [comment]
with the command line **yt-dl** I have used this to prevent "short videos"

--match-filter 'duration > 300'

**Comment by meeb** [comment]
Thanks, @alneven - this would be implemented in tubesync though along with the other match code and an opt-in flag (some crazy people might actually want shorts to download!).

**Comment by timwhite** [comment]
@meeb I think we can close this issue now as we now have length filtering

**Comment by meeb** [comment]
Yep! I would agree. @zpz5HAU-tgc3fgw2xwr you can thank @timwhite for writing the code for this after a year :)

**Comment by alneven** [comment]
thank you, I appreciate it
