### ISSUE TITLE
Migrate `docker login` to actions-docker-login

### ISSUE THREAD

**Issue by kuhnchris** [meeb/tubesync#329]
As there are currently broken builds, we should probabbly refactor the login process to use the official docker login action - which can also be used for GHCR - see https://github.com/docker/login-action for details.

Want me to take a look at it?

**Comment by meeb** [comment]
You're welcome to take a look, but if you mean PR builds fail that's because the "build a container" action is restricted to requiring me to approve it so not every PR immediately results in a live container. The only change really required here is the container build action not be triggered from PRs.

**Comment by kuhnchris** [comment]
So you'd prefer it to only be triggered when you merge into `main`?
```
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
```
Then we'd just remove the "pull_request" entry, IMHO. :-)

**Comment by meeb** [comment]
Fine with me. Honestly I just ignored this issue until now given I was the only person who approved PRs and made releases. If you want to tweak this I have no objections!
