### ISSUE TITLE
Updating YoutubeDL Manually?

### ISSUE THREAD

**Issue by DutchyOven** [meeb/tubesync#36]
Might be a dumb question but is there a way to have tubesync use a more up to date version of youtube or put in fields like cookies.txt into it?

**Comment by meeb** [comment]
There isn't really an easy way to update selected libraries inside of TubeSync which is why it's bundled in the first place. The `:latest` tagged image has up to date `youtube-dl` in it and they'll be an updated versioned release shortly as well. I'll look at adding `cookies.txt` support in a future release. Cheers for the feedback.

**Comment by Code-Slave** [comment]
cookies is almost mandatory if you grab a lot of vids. Im getting constant 429's now. Ive had to go back to my bash scripts for the time being. It might be a good idea to be able to pass a path to an external youtube-dl ?

**Comment by meeb** [comment]
Yeah I've noticed this, will work on it in #38

**Comment by meeb** [comment]
Hi, can you give the `:latest` image a go and see if this reduces or resolves your 429 issues please?

**Comment by DutchyOven** [comment]
> Hi, can you give the `:latest` image a go and see if this reduces or resolves your 429 issues please?

I updated and it was still showing failures. It wasn’t until I reset tasks that it started to work. 

So yes works fine now! Thanks!

**Comment by meeb** [comment]
Excellent, thanks for the feedback. I'll add a feature to clear and reset the tasks on upgrade as well to save people having to manually reset them. I'll close this issue for now as cookies support will be on the longer roadmap and is a different issue.
