### ISSUE TITLE
Media import with .mp4 files causes odd issues and Latest Downloads to be full of garbage

### ISSUE THREAD

**Issue by garbled1** [meeb/tubesync#364]
I ran a media import of my existing youtube channels when setting up tubesync, and it correctly found my .mp4 files, and my .mkv files.  However, now, I have 2 strange issues:

1) My latest downloads list on the dashboard, is full of ancient videos that were imported, with no dates.

2) If I go look at one of those videos, it seems to think the file is a .mkv, when it's actually a .mp4, and then tells me the file size is 0 (in media details).

My guess is that it found the video with the .mp4 name, imported it, and then assumed it had a .mkv name when making the database entry?

I guess I don't care that the media info pages don't work, I just want the latest downloads to work, maybe ignore entries that the system thinks are 0-bytes?

**Comment by meeb** [comment]
The sole use of the media import tool was basically just to link the media item to a file on disk and to set the `is_downloaded` flag to `True` just so that the media item wasn't downloaded again from YouTube. Lots of the other information (metadata, file size and what not) is taken from YouTube which doesn't happen with imported media so yes, if you import media lots of the media information will be blank or missing. Your suggestion sounds fine if imports break the dashboard stats, do you want to submit a PR for it?
