### ISSUE TITLE
No tag for version v0.12.1

### ISSUE THREAD

**Issue by reefland** [meeb/tubesync#372]
It looks like this should be a valid version tag:

![image](https://user-images.githubusercontent.com/16230914/233810834-729a0625-16fd-49fa-bc08-dd81e15b0b2a.png)

However, unable to pull the version tag directly, as `v0.12.1` doesn't exist as a tag.

```
skopeo list-tags docker://ghcr.io/meeb/tubesync

{
    "Repository": "ghcr.io/meeb/tubesync",
    "Tags": [
        "v0.3",
        "v0.4",
        "v0.5",
        "v0.6",
        "v0.7",
        "v0.8",
        "v0.9",
        "v0.9.1",
        "v0.10.0",
        "latest",
        "v0.11.0",
        "v0.12.0"
    ]
}
```

---

```
Failed to pull image "ghcr.io/meeb/tubesync:v0.12.1": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/meeb/tubesync:v0.12.1": failed to resolve reference "ghcr.io/meeb/tubesync:v0.12.1": ghcr.io/meeb/tubesync:v0.12.1: not found
```

**Comment by meeb** [comment]
Please use `:latest` for now. I probably need to switch to date tagged releases.

**Comment by reefland** [comment]
Yeah, I have `:lastest` in use for now.  I have this deployed to my home kubernetes cluster, using GitOps with RenovateBot and ArgoCD, etc.  So using `:lastest` tag is not ideal but working for now.

I personally prefer your existing Semantic Versioning as it is friendly to automated upgrade systems and standard nomenclature to categorize changes (patch, minor, major, etc) so I can set some rules on which get automatically upgraded and which require a manual review and approval. 

Thanks for your work on this project.

**Comment by meeb** [comment]
I usually would properly use semantic versioning but the issue here is a bit unusual. Due to the total reliance on upstream projects to function there may be multiple releases per week to fix issues which is a hassle to manually maintain at the moment. Additionally, every single prior release is going to be immediately broken and useless (due to older `yt-dlp` likely no longer working) so having anyone run older tags just generates a load of "it's not working" support issues.

There's probably a more sensible solution, but for now I've just stuck with "everyone use `:latest`" as a lazy fix. I'm probably going to mirror `yt-dlp`'s dated release tags at some point given tubesync is really just a web UI for `yt-dlp` and `ffmpeg` with some media management logic.

**Comment by reefland** [comment]
Got it.  Thanks for the feedback.
