### ISSUE TITLE
no video supported format and mime type found

### ISSUE THREAD

**Issue by blownco** [meeb/tubesync#398]
Ive got tubesync working great accept for one thing i cant seem to watch the videos in firefox i can watch them in chrome but i hate using chrome i get this error.

anyone else had this happen?

![1383-2039-max](https://github.com/meeb/tubesync/assets/3284604/46acd9d2-e41a-44ac-bf6e-cf95bcbf69a0)

**Comment by meeb** [comment]
That's not specifically a tubesync issue, that just means that your Firefox install doesn't support that 4K AVC1 video stream (which is h264). You likely need to install some additional codecs or otherwise tweak Firefox to make this work. Check your Firefox settings. To test this I'd download the video then right click the file and "open with" Firefox.

**Comment by blownco** [comment]
Thanks for the reply i spent way too long last night and just decided to go back to chrome!

**Comment by meeb** [comment]
No problem, if you do ever find a solution to the issue with Firefox leave a note on this issue for others. I'll close this for now.
