### ISSUE TITLE
Video downloads again after organizing them to different folders

### ISSUE THREAD

**Issue by shreram** [meeb/tubesync#434]
It's not a bug but a question instead. Videos were downloaded successfully and later I organized them into different folders. But when in the next scheduled run, videos are downloaded again. Is there anywany way to save the downloaded filenames to a text file then check against them that flat file to ignore those videos?

I guess the current code only checks if the filename with video-id (key) exists in the current directory. Am I correct?

**Comment by meeb** [comment]
This is probably best with the current method of handling data to mark the media to be skipped before moving it. If flagged to be skipped it shouldn't be downloaded again. Or, modify your paths and file formats such that you don't need to move the files in the first place which would probably be neater.

**Comment by shreram** [comment]
I don't want to go to each media and select **Delete and Skip media**. That's tedious.  Is there any other way? 
Would you recommend updating via SQLite database? I mean change the 'manual_skip' or 'skip' column to 1 in the 'sync_media' table?

**Comment by meeb** [comment]
Yep, stopping the container, updating the `skip` flag to be `True` in `sync_media` will mark everything to be skipped when you start the container again.

**Comment by shreram** [comment]
Thanks for the quick reply. I would like to update this only to one source. What are the differences between 'skip' and 'manual_skip' columns? Just curious.

**Comment by meeb** [comment]
`skip` is generally used to skip media for processing. The skipping is a bit of a mess as it's one of those features that's been slowly added to for two years. `skip` originally was set by the system, such as, the worker would mark media to be skipped if it didn't have any matching media streams or was unavailable after X retries. Then it was added that people could manually unskip media. This caused some issues because the system could reset skip flags or otherwise modify your manual selection such as unskipping media you've set to be skipped or skipping media you've asked to not be skipped. So... there's now a manual skip flag which the system can't change in addition to the skip flag which the system can set. Generally though the `skip` flag is the one used for workers to determine if it should skip the processing of a download or not so set that one. You can set both flags to `True` if you prefer.

**Comment by shreram** [comment]
If anyone would like this approach.
1. Stop the container
2. Take a backup of SQLite database db.sqlite3 
3. Connect to the database via Terminal

```sh
root@drdoof:/mnt/user/appdata/tubesync# sqlite3 db.sqlite3 
```

4. List all sources name and uuid columns from the 'sync_source' table

sqlite> 
```sql
SELECT name,uuid FROM sync_source;
```
5. Find the number of videos using this source in the 'sync_media' table and pass the uuid value from the above query which is next to the source name that you want to update

```sql
SELECT COUNT(*) FROM sync_media WHERE source_id = 'use the uuid output from above query';
```

6. Run this query to update all media that are using this source_id 

```sql
UPDATE sync_media SET skip = 1, manual_skip = 1 WHERE source_id = 'use the uuid output from above query' AND skip = 0 AND manual_skip = 0;
```

7. Close the database
```sh
sqlite> .exit
```
9. Start the container
