### ISSUE TITLE
enhancement: plug-ins for users to add new sites similar to how youtube-dl works

### ISSUE THREAD

**Issue by bobbintb** [meeb/tubesync#46]
I've been working sporadically on a similar python script similar to tubesync, though far more rudimentary. I planned it to basically be a companion to youtube-dl that would scrape the same sites (or the few I'm interested in) and allow you to download the videos, instead of manually collecting them and sending them to youtube-dl. tubesync is far better. I'm a mediocre coder at best anyway. I looked through the FAQ. I saw there was a possibility of including other sites for this. I looked through the code a bit and to see if it modularized similar to how youtube-dl allows you to add more sites like plug-ins. It's fairly easy to just copy an existing one and modify it for a new site. I didn't look in depth but is the youtube specific part of tubesync like this? If it were, other users and devs could easily add new sites with an example template. Although, that may open the flood gates to being overwhelmed by users asking for assistance in development. Just a thought. I'd certainly be willing to contribute a few.

**Comment by meeb** [comment]
Yeah this is what #33 is about really. When I built this I just wanted to support YouTube channels, then it expanded to a few other YouTube URL formats, now in hindsight it should probably support a whole bunch of sites and just chain off of what `youtube-dl` natively already supports rather than re-inventing the URL parsing wheel. If I can use some of the `youtube-dl` parsers what you describe should be possible without any plugins required for TubeSync itself, all the work is already done and probably in a more sensible manner inside of `youtube-dl` already. If this can't work and native local plugins are required then of course any contributions would be welcome, but I suspect I can just stand on the shoulders of `youtube-dl`.

**Comment by bobbintb** [comment]
Ah, ok, cool. I missed that one. I'll check it out.

**Comment by meeb** [comment]
No problem, I'll close this as a dupe for now but feel free to comment if it ends up not doing what you want in the future.
