### ISSUE TITLE
Personal Public Playlists - Error: "'NoneType' object has no attribute 'get'"

### ISSUE THREAD

**Issue by bryanhoffman04** [meeb/tubesync#474]
Both of my public playlists that I created keep returning with:

```
Index media from source "ComedySave" once
Error: "'NoneType' object has no attribute 'get'"
Occured at 2024-02-25 09:26:59
```

I've deleted the youtube playlists and started from scratch and this is still happening.  Not sure why...

Thanks for any advice.

**Comment by meeb** [comment]
This should be fixed in the latest release which should be available in about 30 minutes or so.

**Comment by meeb** [comment]
A

**Comment by meeb** [comment]
Are you sure? This specific bug was fixed. Please paste the log of this occurring and confirm you're running the `:latest` image.

**Comment by meeb** [comment]
The error in your logs doesn't match the error in your screenshot. The errors in your logs are an unauthorized request and one where the format isn't available. Neither of which are an issue with tubesync. Try searching your logs for `Traceback` or `NoneType` etc.

**Comment by meeb** [comment]
I'm not entirely sure what's going on here. That channel works fine for me and your error is unrelated to the original issue. What's happening here is your channel is being indexed, this is apparently returning a list of videos, but for some reason one or more of the videos instead of being `[{... big dictionary of media item data ...}, {... big dictionary of media item data ...}, ...]` it's `[None]`. Your error is because tubesync iterates this list and attempts to extract information from it to index it. In my brief check none of the media items are `None` for me in the returned metadata. Does this error for you?

```bash
$ podman exec -ti tubesync python3 /app/manage.py youtube-dl-info "https://www.youtube.com/channel/UC-EPqVgGmilMJtqKa3kzZNg"
```

It may be something like one media item is unavailable or filtered in your jurisdiction and `yt-dlp` returns a `None` for it or something, but I've not seen this previously. I can easily add a handler to skip `None` media items better but it would be preferable to debug this properly first.

**Comment by meeb** [comment]
OK, I'll add an exception for if some of the media items are returned as `None` to suppress the error so your indexing should partially work. Obviously any media items that have returned `None` won't be downloaded so you may have some missing items from the channel. My best guess really at this point is this is something to do with the data that YouTube is returning for your requests.
