### ISSUE TITLE
Is there a way to not have the folders Video and Audio?

### ISSUE THREAD

**Issue by morpheus2n2** [meeb/tubesync#502]
I was wondering if there's a way to have tubesync use a pre-existing root directory, and then when you add your source it makes a folder like normal from there but so you can have this (this is what I will be using it for more than anything) :-

> -E3 Press Conferences
>     ¬Microsoft
>     ¬Sony
> etc

Instead of the current setting of :-

> -E3 Press Conferences
>      ¬Video
>          ¬Microsoft
>           ¬Sony

etc

**Comment by meeb** [comment]
No, the `video` and `audio` directories are currently hard-coded. They exist because tubesync was designed to work with a media server like Plex or Jellyfin. Without these directories you would be mixing media types in a single media server library (such as, you have a "youtube" video library in Jellyfin which also contains audio files).

What you probably want to do is just mount your directories differently, you can mount directories to any point you like, for example `-v /wherever/you/like/on/host/my-source:/downloads/video/my-source`

**Comment by morpheus2n2** [comment]
Ahh no worries, thanks for the replay :D
