### ISSUE TITLE
My downloads stopped half way through a fairly large list.

### ISSUE THREAD

**Issue by Leopere** [meeb/tubesync#507]
Periodically my watched playlist that's unlisted on YouTube that I use for archiving important videos that might ostensibly get removed from YouTube for miscellaneous reasons stopped working recently it managed to get 900 videos from the playlist but now it's stuck and won't download

well, this isn't the error I came for, but this is happening now.

![image](https://github.com/meeb/tubesync/assets/1068374/5ec9faba-68ec-4c78-92eb-bb4c74ce617a)

**Comment by Leopere** [comment]
Yep this just keeps getting worse I'm going to assume youtube has blocked this downloader.

![image](https://github.com/meeb/tubesync/assets/1068374/b975989e-8485-4a6a-8b5b-9dc467683706)

**Comment by meeb** [comment]
Hi! "expected outfile does not exist" is a generic error that basically means "yt-dlp was called and when it finished the expected download doesn't seem to exist". This can be for pretty much any reason (cookies expired if you're using cookies, local disk is full, YouTube has blocked your IP, basically anything).

Make sure your workers is set to 1 or YouTube will almost certainly block you.

You need to check the container logs to see if you can find the actual error your downloads aren't working.

Obviously stopping the container or pausing the items would be a good idea so you don't just hammer YouTube with falling requests. At least until you know what the actual problem is.

**Comment by Leopere** [comment]
Thanks for the speedy reply.

I haven't used cookies I'm imagining I could though I have YT Premium 
![image](https://github.com/meeb/tubesync/assets/1068374/a76e47c8-3af0-4136-8c29-c69cbb22b22e)
I seem to have a touch more success ensuring the workers are set to 1 but the gunicorn setting is 4 
![image](https://github.com/meeb/tubesync/assets/1068374/44ed8426-5cbb-4068-b867-ed13c849f848)
I would periodically log into this and find 502 errors instead of tubesync so that's where my day started with this.

**Comment by Leopere** [comment]
Okay it vaguely looks like this is going to work I lost my place so I'm apparently redownloading 1500 videos and considering I want more of my life back now from having watched so many at this point...  thanks again for this awesome tool you're "doing gods work"

**Comment by Leopere** [comment]
Yeah every time I re-add GreatScott's Electronics basics it just stops my whole queue

<img width="1363" alt="image" src="https://github.com/meeb/tubesync/assets/1068374/54c357de-967e-498b-a9a0-4b21c568a192">

**Comment by meeb** [comment]
Anything in your container logs when the downloads fail? There should be an actual error somewhere from yt-dlp about why your downloads aren't working.

**Comment by Leopere** [comment]
Overnight it churned through almost all of those video I haven't checked for duplicates but there's 27 downloads pending but no real scrollback in the container logs let me dig deeper.  it looks like the ones left in the list are ones that are only available on the wayback machine is there possibly any plans for you to add a way to pull dead links from the internet archive?

**Comment by Leopere** [comment]
You would be shocked what's replicated to IA I was kind of shocked how often it came up in my list of undownload-ables.  But fair enough thanks for considering it.  It would likely be a lot of work.
