### ISSUE TITLE
Failed to download media

### ISSUE THREAD

**Issue by sonician** [meeb/tubesync#56]
Not sure what I've done wrong, but I am getting this error on every video I attempt:

Failed to download media: cbFJhY5C_lg (UUID: 4dfeac7b-cbf4-4903-af49-131278ddf8b8) to disk, expected outfile does not exist: /home/administrator/tubesync-downloads/20201221_video_1080p-vp9-opus.mkv"

I setup everything following the instructions, and used the following config:

sudo docker run \
  -d \
  --name tubesync \
  -e PUID=1000 \
  -e PGID=1000 \
  -v /home/administrator/tubesync-config:/config \
  -v /home/administrator/tubesync-downloads:/downloads \
  -p 4848:4848 \
  ghcr.io/meeb/tubesync:v0.8
  
I even ensured the administrator account was the owner of /home/administrator and all sub folders, and also tried chmod -R 777 on the tubesync folders. 

It does index the channel properly, but refuses to download. 

The tubesync server is running on an Ubuntu 20.04 VM inside of VirtualBox.

Thank you in advance.

**Comment by meeb** [comment]
That error just means that when the download "completed" the expected output file didn't exist. There's likely some more useful logs explaining what the error is above this line. Anything else useful in your logs?

**Comment by sonician** [comment]
The logs show the following:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 353, in download_media
    raise DownloadFailedException(err)
common.errors.DownloadFailedException: Failed to download media: cbFJhY5C_lg (UUID: 4dfeac7b-cbf4-4903-af49-131278ddf8b8) to disk, expected outfile does not exist: /home/administrator/tubesync-downloads/20201221_test_vacuum-pot-coffee_cbFJhY5C_lg_1080p-vp9-opus.mkv
Rescheduling task Downloading media for "Vacuum Pot Coffee" for 0:01:26 later at 2021-02-18 05:36:21.890122+00:00

**Comment by meeb** [comment]
Can you grep your entire logs for "4dfeac7b-cbf4-4903-af49-131278ddf8b8" or "cbFJhY5C_lg" - that is still just the "expected file doesn't exist" error and not what caused the download to fail in the first place.

**Comment by sonician** [comment]
So it looks like it is a permissions issue on the folder: /home/administrator

I previously created the two default folders /home/administrator/tubesync-downloads and /home/administrator/tubesync-config, and pointed to them in the docker config. I confirmed the administrator id is 1000.

2021-02-18 01:34:55,054 [tubesync/INFO] Downloading media: cbFJhY5C_lg (UUID: 4dfeac7b-cbf4-4903-af49-131278ddf8b8) to: "/home/administrator/tubesync-downloads/20201221_test_vacuum-pot-coffee_cbFJhY5C_lg_1080p-vp9-opus.mkv"
ERROR: unable to create directory [Errno 13] Permission denied: '/home/administrator'
2021-02-18 01:34:55,882 [tubesync/ERROR] Failed to download media: cbFJhY5C_lg (UUID: 4dfeac7b-cbf4-4903-af49-131278ddf8b8) to disk, expected outfile does not exist: /home/administrator/tubesync-downloads/20201221_test_vacuum-pot-coffee_cbFJhY5C_lg_1080p-vp9-opus.mkv
Rescheduling Downloading media for "Vacuum Pot Coffee"

**Comment by meeb** [comment]
OK, yep, that does indeed look like the file doesn't exist because it doesn't have permission to write to the output directory. Check the UID and GID TubeSync is running under in the container in the Runtime Information section at the bottom of the dashboard, that's taken in real time and accurate.

I would guess you've just typo'd something somewhere and there's just a UID or permission issue somewhere you've not spotted. That error is raised directory from the OS layer (e.g. a `fopen()` call failing), so it's nothing TubeSync is doing so it would be your deployment / setup.

Obvious debugging steps, what permissions does `/home` have? What permissions and ownership does `/home/administrator` have? etc. That sort of thing.

**Comment by sonician** [comment]
Good news, I created a brand new download folder under /media/ and set the owner as 1000:1000 and the download is now working.

Not sure why it wasn't under /home/administrator/, with the same permissions. 

When setting the sources "directory" value, does it just need to be the subfolder off the main downloads, or the full path (I was initially putting in the full path, but only the "subfolder" for this source, with the new /media/tubesync-downloads folder.

Thank you for your help!

**Comment by meeb** [comment]
Glad you solved it. The `directory` box when you add a source is "just" the directory name, like `my-channel`. It should not be a full directory path. The full path is handled for you. That may have been the first permissions problem you encountered if you were entering a full directory path there. I'll close this issue for now but feel free to re-open the issue if you encounter further problems.

**Comment by ExodusC** [comment]
I know this is a closed issue, but rather than opening a new one, I wanted to report I'm having this error get thrown a lot as well. I don't -think- it's permissions-related, as the bulk of videos from sources I have added will download successfully. As an example, I have a source with 393 videos, of which 385 will download properly, with the remainder throwing the same error and showing as permanently "Downloading" in the UI.

Here's an example piece of media: https://www.youtube.com/watch?v=wLjle8ITGFo

I did a bit of troubleshooting, but first here's some example output from the container for one of the videos in question:

<html><body>


2021-08-09 22:41:17 | stdout | Rescheduling task Downloading media for "SM64 - Chill with the Bully - 0x A Presses" for 0:21:41 later at 2021-08-09 23:02:58.009729+00:00
-- | -- | --
2021-08-09 22:41:17 | stdout | common.errors.DownloadFailedException: Failed to download media: wLjle8ITGFo (UUID: ff8de81a-a605-43e2-9475-f30f815ab9cb) to disk, expected outfile does not exist: /downloads/video/pannenkoek2012/2013-09-22_pannenkoek2012_sm64-chill-with-the-bully-0x-a-presses_wLjle8ITGFo_1080p-vp9-mp4a.mkv
2021-08-09 22:41:17 | stdout | raise DownloadFailedException(err)
2021-08-09 22:41:17 | stdout | File "/app/sync/tasks.py", line 403, in download_media
2021-08-09 22:41:17 | stdout | func(*args, **kwargs)
2021-08-09 22:41:17 | stdout | File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
2021-08-09 22:41:17 | stdout | Traceback (most recent call last):
2021-08-09 22:41:17 | stdout | Rescheduling Downloading media for "SM64 - Chill with the Bully - 0x A Presses"
2021-08-09 22:41:17 | stdout | 2021-08-09 18:41:17,000 [tubesync/ERROR] Failed to download media: wLjle8ITGFo (UUID: ff8de81a-a605-43e2-9475-f30f815ab9cb) to disk, expected outfile does not exist: /downloads/video/pannenkoek2012/2013-09-22_pannenkoek2012_sm64-chill-with-the-bully-0x-a-presses_wLjle8ITGFo_1080p-vp9-mp4a.mkv
2021-08-09 22:41:16 | stdout | 2021-08-09 18:41:16,995 [tubesync/INFO] [youtube-dl] finished downloading: 2013-09-22_pannenkoek2012_sm64-chill-with-the-bully-0x-a-presses_wLjle8ITGFo_1080p-vp9-mp4a.mkv.f140 - 371.76KiB in ?
2021-08-09 22:41:16 | stdout | ERROR: giving up after 0 fragment retries
2021-08-09 22:41:15 | stdout | 2021-08-09 18:41:15,966 [tubesync/INFO] Downloading media: wLjle8ITGFo (UUID: ff8de81a-a605-43e2-9475-f30f815ab9cb) to: "/downloads/video/pannenkoek2012/2013-09-22_pannenkoek2012_sm64-chill-with-the-bully-0x-a-presses_wLjle8ITGFo_1080p-vp9-mp4a.mkv"

</body>
</html>


Here's the data from the TubeSync UI, just to show that it detects the formats correctly and such, and marks that it should be able to be downloaded:


<html><body>


Duration | 00:00:23
-- | --
Desired format | 1080p (video:VP9, audio:OPUS) 60FPS
Fallback | Get next best resolution or codec instead
Downloaded? |  
Can download? |  
Available formats | ID: 139                          , audio:mp4a.40.5 @k / 22050Hz                                                           ID: 140                          , audio:mp4a.40.2 @129.731k / 44100Hz             (matched)                                              ID: 160             , 144p (192x144), fps:30, video:avc1.4d400c @77.746k                                                                        ID: 278             , DASH video (192x144), fps:30, video:vp9 @95.0k                                                                        ID: 133             , 240p (320x240), fps:30, video:avc1.4d400d @156.639k                                                                        ID: 242             , DASH video (320x240), fps:30, video:vp9 @220.5k                                                                        ID: 134             , 360p (480x360), fps:30, video:avc1.4d401e @362.589k                                                                        ID: 243             , DASH video (480x360), fps:30, video:vp9 @405.72k                                                                        ID: 135             , 480p (640x480), fps:30, video:avc1.4d401e @664.0k                                                                        ID: 244             , DASH video (640x480), fps:30, video:vp9 @752.64k                                                                        ID: 136             , 720p (960x720), fps:30, video:avc1.4d401f @1286.324k                                                                        ID: 247             , DASH video (960x720), fps:30, video:vp9 @1505.28k                                                                        ID: 248             , DASH video (1440x1080), fps:30, video:vp9 @2646.0k                          (matched)                                              ID: 137             , 1080p (1440x1080), fps:30, video:avc1.640028 @2662.45k                                                                        ID: 18             , 360p (480x360), fps:30, video:avc1.42001E @634.852k             , audio:mp4a.40.2 @k / 44100Hz                                                           ID: 22             , 720p (960x720), fps:30, video:avc1.64001F @1415.77k             , audio:mp4a.40.2 @k / 44100Hz
Matched formats | Combined: no match           Audio: 140 (fallback)           Video: 248 (fallback)


</body>
</html>


So, my testing led me to go ahead and try to use youtube-dl/ffmpeg on my desktop:


```
PS D:\YTDL> .\youtube-dl.exe https://www.youtube.com/watch?v=wLjle8ITGFo -F
[youtube] wLjle8ITGFo: Downloading webpage
[youtube] wLjle8ITGFo: Downloading MPD manifest
[info] Available formats for wLjle8ITGFo:
format code  extension  resolution note

139          m4a        audio only DASH audio   50k , m4a_dash container, mp4a.40.5 (22050Hz), 141.13KiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 371.76KiB
160          mp4        192x144    144p   77k , mp4_dash container, avc1.4d400c@  77k, 30fps, video only, 221.98KiB
278          webm       192x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
133          mp4        320x240    240p  156k , mp4_dash container, avc1.4d400d@ 156k, 30fps, video only, 447.24KiB
242          webm       320x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
134          mp4        480x360    360p  362k , mp4_dash container, avc1.4d401e@ 362k, 30fps, video only, 1.01MiB
243          webm       480x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
135          mp4        640x480    480p  664k , mp4_dash container, avc1.4d401e@ 664k, 30fps, video only, 1.85MiB
244          webm       640x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
136          mp4        960x720    720p 1286k , mp4_dash container, avc1.4d401f@1286k, 30fps, video only, 3.59MiB
247          webm       960x720    DASH video 1505k , webm_dash container, vp9, 30fps, video only
248          webm       1440x1080  DASH video 2646k , webm_dash container, vp9, 30fps, video only
137          mp4        1440x1080  1080p 2662k , mp4_dash container, avc1.640028@2662k, 30fps, video only, 7.42MiB
18           mp4        480x360    360p  634k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 1.78MiB
22           mp4        960x720    720p 1415k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
```

After verifying my local copy of youtube-dl was seeing the same format selection just to sanity check, I went ahead and tried to force the video format TubeSync had selected:

```
PS D:\YTDL> .\youtube-dl.exe https://www.youtube.com/watch?v=wLjle8ITGFo -f 248
[youtube] wLjle8ITGFo: Downloading webpage
[youtube] wLjle8ITGFo: Downloading MPD manifest
[dashsegments] Total fragments: 6
[download] Destination: SM64 - Chill with the Bully - 0x A Presses-wLjle8ITGFo.webm
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries
PS D:\YTDL>
```

My uneducated guess is that based on this, either the first fragment, or the entire video in the selected codec isn't actually available from YouTube's servers. I'm able to download with other codec selections.

However, my question is, how can/should TubeSync ideally handle edge cases like this? I think at the bare minimum, having some kind of fail-safe behavior after enough failures to download, or providing some kind of output to the GUI would be useful.

If this should be in a dedicated issue, since it seems like the problem here isn't the same as the OP's, I can repost it.

**Comment by meeb** [comment]
You are correct that media in that format is actually broken on YouTube, the manifest for the DASH video straight up contains broken links. Internally, what TubeSync does is call the `youtube-dl` API to download to the specified output file path, wait for it to complete then checks the file exists. That's about it. A `DownloadFailedException` is raised simply if the expected output file doesn't exist for whatever reason, which could be anything (disk full, proxy failed, `youtube-dl` out of date and can't talk to Youtube etc.). It is possible to attempt to detect certain classes of `youtube-dl` failures and attempt to work around them, but this would mean, for example, instead of retrying a temporary error TubeSync might then just pick the next best codec combination and get that if it's available rather than potentially just retrying successfully with the desired codecs at a later date.

As this is a compromise between retrying for temporary failures or having to work around (hopefully the quite rare) actually broken media on YouTube I'm *probably* leaning towards leaving it as a manual fix for media that's actually broken. If it's a real problem for people though I'll look into what error data is available from the `youtube-dl` API and have a go at some fuzzy automated error work-arounds.

Thanks for the comment certainly an interesting one to find.
