### ISSUE TITLE
Allow "Episode" file format when adding media source

### ISSUE THREAD

**Issue by Jay2645** [meeb/tubesync#58]
Basically, just a request to allow for an "episode" based on either playlist order (if the source is a playlist) or how old the video is (in the case of a channel).

My use-case is uploading libraries to Plex which have entries already in the TVDB -- for example, the show Critical Role [has a TVDB entry](https://thetvdb.com/series/critical-role/seasons/official/2), but the playlist all the Critical Role videos get uploaded to doesn't have a good naming convention that Plex auto-detects.

Generally, I use Filebot to rename my media files to the format {Show Name} - S{Season Number}E{Episode Number} - {Episode Name}.{ext}. I can hardcode the Show Name and Season Number (plus use {title_full} for the episode name), but I can't specify episode number anywhere, as far as I can see.

**Comment by meeb** [comment]
Can you link me to an example channel or playlist? I can add this as a feature but only if it's presented in the metadata available from YouTube. I can add a semi-incremental number based on when it was added to TubeSync (as neither position in channel nor position in playlist are static and can change when re-indexed) that's about the best you can do without either explicit season and episode info from YouTube. This could get a bit mad though with large channels with things like S01E2389 occurring.

**Comment by Jay2645** [comment]
Yeah, [here's the example that was giving me trouble.](https://www.youtube.com/watch?v=byva0hOj8CU&list=PL1tiwbzkOjQxD0jjAE7PsWoaCrs0EkBH2) I was thinking just using the index of the file in the playlist as the episode number, but you're right that with giant channels it could be a bit crazy.

**Comment by meeb** [comment]
It's not just that it could get crazy huge, the order in the playlist is arbitrary and user-defined so if the playlist owner suddenly changes it to "order by most popular" rather than "order by date" and adds 10 more videos, on the next index TubeSync is going to have no way to index them properly short of physically re-assigning new episode numbers to all the media entries and renaming all the files on disk as what TubeSync has classed as S01E22 might now be S01E2392 in the remote playlist ordering and an entirely different media item is S01E22.

I can add an unchanging per-source incrementing counter as an "episode" number, which would generally make sense providing the playlist being indexed doesn't get changed much other than adding new recent content and the playlist is default ordered by date, but yeah that's about it. It would get extremely messy and error prone to rely on remote ordering.

I've had a look at your example playlist and they do not have the season or episode information properly set in their YouTube metadata either so unfortunately I can't add that in either. They have a tag set of "campaign 2 episode 31" but attempting to parse arbitrary user tags to extract this (on the extremely rare occasion season / episode info set via tags) probably isn't a sensible idea.

Would an immutable, auto-incrementing integer per source media item be useful for what you want?

**Comment by Jay2645** [comment]
Yeah, I think something like that would be perfect!

**Comment by meeb** [comment]
I've added a separate issue for this with #60 with a more detailed description (mostly with details to jog my memory in the future). You're welcome to track the issue there and I'll bundle it into the v1.0 release.

I'll close this for now.

Oh just to clarify I can added a "season" file name variable, but it would be literally just hard-coded as "01" so it could be a bit pointless.

**Comment by Jay2645** [comment]
I'm fine with handling the season manually, since generally each season is a different source anyway. Thank you so much!
