### ISSUE TITLE
Cookie function broken because of outdated yt-dlp

### ISSUE THREAD

**Issue by FaySmash** [meeb/tubesync#608]
The function of using a cookies.txt file is currently completely broken because of recent youtube changes. yt-dlp already [contains a fix for this](https://github.com/yt-dlp/yt-dlp/issues/11640) (changing default behavior for the cookie argument) but the latest release version of tubesync has a way too outdated yt-dlp version.

**Comment by meeb** [comment]
The version of yt-dlp in tubesync when you reported this was two weeks old. Either way, this is updated now.

**Comment by FaySmash** [comment]
> The version of yt-dlp in tubesync when you reported this was two weeks old. Either way, this is updated now.

The latest release is still v0.13.7 from August so if the image gets pulled from the ghcr.io with the :latest tag, it will still contain a 4 month old yt-dlp version, so isn't this issue still valid until the v0.13.8 release?
Also happy Holidays

**Comment by meeb** [comment]
It's strongly advisable to use the `:latest` tag. As tubesync pretty much updates whenever `yt-dlp` does it gets updated frequently. I'm pondering switching to YYYY-MM-DD style versioning rather than semantic. The `:latest` tag will be from a few days ago.

I effectively just do a semantic version release when there's been enough features added to make it worth while.
