### ISSUE TITLE
No Media to Index?

### ISSUE THREAD

**Issue by storm-father** [meeb/tubesync#87]
I'm trying to pull some videos from my favorite poker vloggers and keep running into this error. I've tried multiple channels, set the resolution fallback to codec, changed audio type, tried the long channel id's and also their personalized ones. 

I haven't tried playlists because none of them have those. 

What should I try next?

 Index media from source "Mariano Poker", attempted 4 times
Error: "Source "Mariano Poker" (ID: 1380822e-2143-4e7f-9b7b-f3e5bff2109a) returned no media to index, is the source key valid? Check the source configuration is correct and that the source is reachable"
 Task will be retried at 2021-03-04 16:17:02

**Comment by storm-father** [comment]
I found a playlist and it fetched that just fine.

**Comment by meeb** [comment]
This is likely due to `youtube-dl` requiring an update. Please try `:latest`.

**Comment by storm-father** [comment]
> This is likely due to `youtube-dl` requiring an update. Please try `:latest`.

I have it installed on unraid. 

 TubeSync version 0.9 with  youtube-dl version 2021.02.10 and  FFmpeg version 4.3.1-static.

**Comment by Ateroz** [comment]
Unraid acts up with ghcr.io in my experience. If you're sure your template is running latest instead of the default v0.9, you should try going to advanced view on your docker tab and do a forced update.

**Comment by storm-father** [comment]
![Uploading 87768599-ABB6-40CB-9564-25E1CC0D7D9C.jpeg…]()

**Comment by storm-father** [comment]
![59BE1EBB-865D-40C1-A77C-06DA68B81D18](https://user-images.githubusercontent.com/79737959/110056727-2e079980-7d14-11eb-8f2f-c7b87dd2e1c3.jpeg)

**Comment by Ateroz** [comment]
your template is still on v0.9, you need to change the tag to latest
![image](https://user-images.githubusercontent.com/5369885/110056802-75e6ea80-7d2d-11eb-8d15-accc6e5f3beb.png)

**Comment by storm-father** [comment]
Thanks, guys. Please excuse my ignorance 😆 Working like a charm now. Really appreciate it.

**Comment by meeb** [comment]
No-one should use the `:latest` really it has dev work in it, but TubeSync is still in alpha so that's where fixes are. This will get better over time. I'll push another release today at some point. I've also never used unraid so that's nothing directly related to this project really. When stable, TubeSync will have regular releases to update `youtube-dl` so I suspect pinned tags may not be the way forward in the end. In the interim though, you can use `:latest` or you can use the slightly more stable tagged releases and accept they might break for a day or two at a time during alpha development. Glad you got it working for you in the end!

**Comment by meeb** [comment]
Also just to clarify I didn't make any templates or anything for Unraid, so any issues there are not anything I've done :)

**Comment by meeb** [comment]
The new `:0.9.1` release is a minor release but contains the same updated `youtube-dl` as `:latest` if you prefer to use tags for the moment. Either way, issue should be fixed so I'll close this for now. Feel free to create a new issue or re-open this one if your issue persists.

**Comment by meeb** [comment]
Hi @MatthK, this sounds like a different issue with similar end symptoms. Can you check what's in your logs? It'll tell you what the actual error is not just the very last one you get in the dashboard.

```bash
$ docker logs tubesync
```

From a terminal and look for suitably important error messages.

**Comment by MatthK** [comment]
I tried, but there is nothing related to the failing of the sync.
And although it says there are permanent errors, there is no error message showing at the bottom. I know I saw it previously, but probably due to the update, it doesn't show anymore?

Now, when I am in the source, it just says: `This source has encountered permanent failures listed at the bottom of this page, check its settings`. But there is no error message at the bottom.

I searched for "error" in the log file, and the only error I see is for some videos it couldn't download (on the channel that I recreated and is now updating). Also for "warn" didn't show any relevant hits. I restarted the container, and edited/saved the channel to hopefully trigger something in the log, but no sign there.

**Comment by meeb** [comment]
Ah, so currently if a source permanently fails it may just get marked as broken and not indexed again. Try the "reset tasks" button on the tasks page in the dashboard, and watch the `docker logs tubesync` while you do it. That will pretty much reset all the queued tasks including the indexing.

**Comment by MatthK** [comment]
Resetting the tasks did the trick. Thank you very much.

**Comment by meeb** [comment]
@MatthK for some background, the original logic of TubeSync just assumes that if some 20+ attempts to index all the videos on a channel fails that something is permanently broken (like someone put in the wrong channel name or some other never-fixable problem). This has turned out to be a bit over-zealous when you get 2-3 days of throttling by YouTube in some cases, indexing fails 20+ times and the channel gets permanently marked as broken when it really isn't. I plan on adding some sort of soft retry after X days feature to test permanently broken channels as a one-off to check to see if they really are broken or if it was just a very extended temporary problem, but in the interim the reset tasks button will just force-clear all the errors and make TubeSync retry everything from scratch.
