### ISSUE TITLE
videos not being removed from share when time to auto delete

### ISSUE THREAD

**Issue by stilltruckin** [meeb/tubesync#99]
Hi Meeb,

On all my sources none of the videos are being removed from the share when it's time for them to auto delete. They are no longer showing in the media tab and are only listed in the skipped video section, but the files themselves are never removed from the folder share. There aren't any issues with permissions for the share. Nor did I find any errors in the logs.  

Running on unraid 6.9.1 and tubesync:v0.9.1

**Comment by meeb** [comment]
Hi, the file deletion should work quite reliably. If the file deletion is triggering properly there should be something in the logs if the file can't be deleted. Can you confirm the sources have their delete old videos flag set as well as the date cap?

**Comment by meeb** [comment]
Ah, how many media items are in your sources? If they are large channels with a lot of media you are likely being affected by performance issues which are scheduled to be fixed in issues like #93, #94 and #72 - that is the back end is exceeding 60 seconds before the task is complete and doesn't get around to finishing some tasks. If this is the case it's unfortunately annoying for you in the short term but the good news is that it will be fixed before the 1.0 release.

**Comment by StillTruckin** [comment]
They are large channels. 

That is good news about v1.0 Thanks!

**Comment by meeb** [comment]
This should have been fixed for some time. Please open a new issue if you still experience this.
